env:
  browser: true
  es6: true
extends: htmlacademy/es6
globals:
  $: readonly
overrides:
  - files: [gulpfile.js, ./gulp/**/*.js]
    env:
      node: true
    parserOptions:
      sourceType: 'script'
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  max-len:
    - error
    - code: 100
      ignoreComments: false
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreUrls: true
      tabWidth: 2
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
