---
  extends:
    - yialo/preset-webpack
  globals:
    process: readonly
  ignorePatterns:
    - '*.html'
    - /build/
  overrides:
    - extends:
        - yialo/mixin-jest
      files:
        - './**/*.{spec,test}.[jt]s?(x)'
        - './**/__tests__/**/*.[jt]s?(x)'
    - extends:
        - yialo/preset-node
      files:
        - ./*.js
    - extends:
        - yialo/mixin-typescript
      files:
        - ./source/**/*.ts?(x)
  rules:
    import/no-unassigned-import:
      - error
      - allow:
        - '**/*.{?(s)css,jp?(e)g,png,svg}'
  settings:
    import/resolver: webpack
