env:
  browser: true
  commonjs: true
  es6: true
extends: htmlacademy/es6
rules:
  max-len:
    - error
    - code: 100
      ignoreComments: false
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreUrls: true
      tabWidth: 2
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
